services:
  postgres:
    container_name: postgres-container
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - microservice-network
      - postgres
    restart: unless-stopped

  pgadmin:
      container_name: pgadmin-container
      image: dpage/pgadmin4:latest
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      volumes:
        - pgadmin:/var/lib/pgadmin
      networks:
        - microservice-network
        - postgres
      restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - microservice-network
      - postgres

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-container
    ports:
      - 9411:9411
    networks:
      - microservice-network
      - postgres

networks:
  microservice-network:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: